application: keyczar-home
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: webpage/index.html
  upload: webpage/index.html

- url: /(.*)
  static_files: webpage/\1
  upload: webpage/(.*)
